language: rust
rust:
  - stable
  - beta
# cache: cargo
before_script:
  - rustup component add rustfmt clippy
script:
  - cargo fmt --verbose -- --check
  - cargo clippy --verbose
  - cargo test --verbose
