# unstable_features = true
# format_code_in_doc_comments = true
# format_macro_matchers = true
# format_macro_bodies = true
# format_strings = true
# merge_imports = true
newline_style = "Unix"
# normalize_comments = true
# normalize_doc_attributes = true
use_field_init_shorthand = true
use_try_shorthand = true
# wrap_comments = true
