commit = "8296db887368bbffa3379f995a1e628ddbe8421f"

[ignored]
# Not implemented yet:
flags = []

features = [
    ### Unimplemented features:

    "FinalizationRegistry",
    "IsHTMLDDA",
    "symbols-as-weakmap-keys",
    "Intl.DisplayNames",
    "Intl.RelativeTimeFormat",
    "Intl-enumeration",

    ### Pending proposals

    # https://github.com/tc39/proposal-is-error
    "Error.isError",

    # https://github.com/tc39/proposal-intl-locale-info
    "Intl.Locale-info",

    # https://github.com/tc39/proposal-regexp-legacy-features
    "legacy-regexp",

    # Import Attributes
    # https://github.com/tc39/proposal-import-attributes/
    "import-attributes",

    # https://github.com/tc39/proposal-import-attributes
    "import-assertions",

    # https://tc39.es/proposal-defer-import-eval
    "import-defer",

    # https://github.com/tc39/proposal-iterator-sequencing
    "iterator-sequencing",

    # https://github.com/tc39/proposal-json-modules
    "json-modules",

    # https://github.com/tc39/proposal-realms
    "ShadowRealm",

    # https://github.com/tc39/proposal-intl-duration-format
    "Intl.DurationFormat",

    # https://github.com/tc39/proposal-decorators
    "decorators",

    # https://github.com/tc39/proposal-duplicate-named-capturing-groups
    "regexp-duplicate-named-groups",

    # https://github.com/tc39/proposal-array-from-async
    "Array.fromAsync",

    # https://github.com/tc39/proposal-json-parse-with-source
    "json-parse-with-source",

    # RegExp.escape
    # https://github.com/tc39/proposal-regex-escaping
    "RegExp.escape",

    # https://github.com/tc39/proposal-iterator-helpers
    "iterator-helpers",

    # Set methods
    # https://github.com/tc39/proposal-set-methods
    "set-methods",

    # Uint8Array Base64
    # https://github.com/tc39/proposal-arraybuffer-base64
    "uint8array-base64",

    ### Non-standard
    "caller",
]

tests = ["sm"]
