commit = "7d0f906f4bef32bad3d6cce30c53978e26d8d10c"

[ignored]
# Not implemented yet:
flags = []

features = [
    ### Unimplemented features:

    "FinalizationRegistry",
    "IsHTMLDDA",
    "symbols-as-weakmap-keys",
    "Intl.DisplayNames",
    "Intl.RelativeTimeFormat",
    "Intl-enumeration",
    "Intl.DurationFormat",
    "regexp-duplicate-named-groups",
    "iterator-helpers",
    "explicit-resource-management",
    "joint-iteration",

    ### Pending proposals

    # https://github.com/tc39/proposal-intl-locale-info
    "Intl.Locale-info",

    # https://github.com/tc39/proposal-regexp-legacy-features
    "legacy-regexp",

    # https://github.com/tc39/proposal-defer-import-eval
    "import-defer",

    # https://github.com/tc39/proposal-iterator-sequencing
    "iterator-sequencing",

    # https://github.com/tc39/proposal-realms
    "ShadowRealm",

    # https://github.com/tc39/proposal-decorators
    "decorators",

    # https://github.com/tc39/proposal-json-parse-with-source
    "json-parse-with-source",

    # Uint8Array Base64
    # https://github.com/tc39/proposal-arraybuffer-base64
    "uint8array-base64",

    # Source Phase Imports
    # https://github.com/tc39/proposal-source-phase-imports
    "source-phase-imports",
    # test262 special specifier
    "source-phase-imports-module-source",

    # Immutable Array Buffer
    # https://github.com/tc39/proposal-immutable-arraybuffer
    "immutable-arraybuffer",

    # Non-extensible Applies to Private
    # https://github.com/tc39/proposal-nonextensible-applies-to-private
    "nonextensible-applies-to-private",

    ### Non-standard
    "caller",
]

tests = [
    # Should throw an OOM error instead of filling the whole RAM.
    "test/staging/sm/String/replace-math.js",
    # Panics
    "test/staging/sm/expressions/optional-chain-first-expression.js",
    "test/staging/sm/regress/regress-554955-2.js",
    "test/staging/sm/class/fields-static-class-name-binding-eval.js",
    "test/staging/sm/regress/regress-554955-1.js",
    "test/staging/sm/regress/regress-554955-3.js",
    # Extension canonicalization not yet supported by ICU4X.
    # TODO: Remove when https://github.com/unicode-org/icu4x/issues/3483 is fixed.
    "test/intl402/Intl/getCanonicalLocales/non-iana-canon.js",
    "test/intl402/Intl/getCanonicalLocales/unicode-ext-canonicalize-measurement-system.js",
    "test/intl402/Intl/getCanonicalLocales/unicode-ext-canonicalize-col-strength.js",
    "test/intl402/Intl/getCanonicalLocales/unicode-ext-canonicalize-calendar.js",
    "test/intl402/Intl/getCanonicalLocales/unicode-ext-canonicalize-timezone.js",
    "test/intl402/Intl/getCanonicalLocales/transformed-ext-canonical.js",
    # h24 hour cycle not supported by ICU4X.
    # TODO: Remove when https://github.com/unicode-org/icu4x/issues/6597 is fixed.
    "test/intl402/Locale/getters.js",
    "test/intl402/Locale/constructor-getter-order.js",
    "test/intl402/Locale/constructor-options-hourcycle-valid.js",
    # Extension canonicalization not yet supported by ICU4X.
    # TODO: Remove when https://github.com/unicode-org/icu4x/issues/3483 is fixed.
    "test/intl402/Locale/prototype/calendar/canonicalize.js",
    "test/intl402/Locale/constructor-non-iana-canon.js",
    "test/intl402/Locale/constructor-options-canonicalized.js",
]
