commit = "7d0f906f4bef32bad3d6cce30c53978e26d8d10c"

[ignored]
# Not implemented yet:
flags = []

features = [
    ### Unimplemented features:

    "FinalizationRegistry",
    "IsHTMLDDA",
    "symbols-as-weakmap-keys",
    "Intl.DisplayNames",
    "Intl.RelativeTimeFormat",
    "Intl-enumeration",
    "Intl.DurationFormat",
    "regexp-duplicate-named-groups",
    "iterator-helpers",
    "explicit-resource-management",
    "joint-iteration",

    ### Pending proposals

    # https://github.com/tc39/proposal-intl-locale-info
    "Intl.Locale-info",

    # https://github.com/tc39/proposal-regexp-legacy-features
    "legacy-regexp",

    # https://github.com/tc39/proposal-defer-import-eval
    "import-defer",

    # https://github.com/tc39/proposal-iterator-sequencing
    "iterator-sequencing",

    # https://github.com/tc39/proposal-realms
    "ShadowRealm",

    # https://github.com/tc39/proposal-decorators
    "decorators",

    # https://github.com/tc39/proposal-json-parse-with-source
    "json-parse-with-source",

    # Source Phase Imports
    # https://github.com/tc39/proposal-source-phase-imports
    "source-phase-imports",
    # test262 special specifier
    "source-phase-imports-module-source",

    # Immutable Array Buffer
    # https://github.com/tc39/proposal-immutable-arraybuffer
    "immutable-arraybuffer",

    # Non-extensible Applies to Private
    # https://github.com/tc39/proposal-nonextensible-applies-to-private
    "nonextensible-applies-to-private",

    ### Non-standard
    "caller",
]

tests = [
    # Should throw an OOM error instead of filling the whole RAM.
    "test/staging/sm/String/replace-math.js",
    # Panics
    "test/staging/sm/expressions/optional-chain-first-expression.js",
    "test/staging/sm/regress/regress-554955-2.js",
    "test/staging/sm/class/fields-static-class-name-binding-eval.js",
    "test/staging/sm/regress/regress-554955-1.js",
    "test/staging/sm/regress/regress-554955-3.js",

    # 1. stop-before-partial is unsupported
    # 2. partial-write/read semantics is unsupported in setFromBase64
    "test/built-ins/Uint8Array/fromBase64/last-chunk-handling.js",
    "test/built-ins/Uint8Array/fromBase64/last-chunk-invalid.js",
    "test/built-ins/Uint8Array/prototype/setFromBase64/last-chunk-handling.js",
    "test/built-ins/Uint8Array/prototype/setFromBase64/subarray.js",
    "test/built-ins/Uint8Array/prototype/setFromBase64/target-size.js",
    "test/built-ins/Uint8Array/prototype/setFromBase64/trailing-garbage.js",
    "test/built-ins/Uint8Array/prototype/setFromBase64/writes-up-to-error.js",
]
