[package]
name = "boa_macros"
description = "Macros for the Boa JavaScript engine."
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
cow-utils.workspace = true
quote.workspace = true
syn = { workspace = true, features = ["full"] }
proc-macro2.workspace = true
synstructure.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
