[package]
name = "boa_gc"
version = "0.13.0"
edition = "2021"
rust-version = "1.58"
authors = ["boa-dev"]
description = "Garbage collector used in Boa."
repository = "https://github.com/boa-dev/boa"
keywords = ["javascript", "js", "garbage", "memory"]
categories = ["command-line-utilities"]
license = "Unlicense/MIT"
exclude = [
    "../.vscode/*",
    "../.editorconfig",
    "../test262/*",
    "../node_modules/*",
    "../target/*",
    "../dist/*",
    "../.github/*",
    "../assets/*",
    "../docs/*",
    "../*.js",
    "../test_ignore.txt",
    "../yarn.lock",
    "../package.json",
    "../index.html",
    "../tests/*",
    "../.github/*",
]

[dependencies]
gc = { version = "0.4.1", features = ["derive"] }

# Optional Dependencies
measureme = { version = "10.0.0", optional = true }
